### ISSUE TITLE
gflags.exceptions.UnparsedFlagAccessError: Trying to access flag sc2_run_config before flags were parsed.

### ISSUE THREAD

**Issue by SoyGema** [chris-chris/pysc2-examples#8]
Hi there!
Thanks for adding this useful project for pysc2 .

After cloning the repo and solve some requirement and installation issues, It appears the following error when training the map, in both deepq and acktr.

Can you point what to do here? 
Many thanks !

**Comment by SoyGema** [comment]
It raises the same error for defeat_zearlings however it seems to work in the training phase

**Comment by yilei** [comment]
Try the latest code? Did https://github.com/chris-chris/pysc2-examples/pull/7 fix the issue?

**Comment by chris-chris** [comment]
Try install the latest library from git.

$ pip install git+https://github.com/deepmind/pysc2

$ pip install git+https://github.com/openai/baselines

**Comment by chris-chris** [comment]
@SoyGema 
I found and fixed a bug due to pysc2 version mismatch!
Please pull the latest master branch code :)

**Comment by ViktorM** [comment]
Have the same error. Just installed pysc2 and have everything the latest.

**Comment by SoyGema** [comment]
Thanks.
